#!/usr/bin/env bash
#Displays "To infinity and beyond indefinitely", sleep 2 and print I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
