#!/usr/bin/env bash
# Display "Holberton School" 10 times
i=0
while [ $i -lt 10 ]
do
     if [ $i -eq 3 ]
     then
         echo "bad luck"
     elif [ $i -eq 7 ]
     then
	 echo "good luck"
     else
	 echo "Holberton School"
     fi
      let i++
done
