#!/usr/bin/env bash
# Display "Holberton School" 10 times
h=0
while [ $h -le 12 ]
do
     echo "Hour: $h"
     m=1
     while [ $m -le 59 ]
     do
         echo $m
         let m++
     done
let h++
done
