#!/usr/bin/env bash
#Script that configures an Ubuntu server with new requirements.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
tee -a ~/hosts.new <<< "8.8.8.8 facebook.com" > /dev/null
cp -f ~/hosts.new /etc/hosts
